# Generated by Django 3.1.7 on 2021-03-29 12:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=512, null=True)),
                ('client_id', models.CharField(max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='OneWireInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512, null=True)),
                ('pin_number', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'verbose_name': 'OneWireInterface',
                'verbose_name_plural': 'OneWireInterfaces',
            },
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('pin_number', models.IntegerField()),
                ('description', models.CharField(max_length=512, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'verbose_name': 'Relay',
                'verbose_name_plural': 'Relays',
            },
        ),
        migrations.CreateModel(
            name='TempSensor',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(max_length=512, null=True)),
                ('total_bad', models.IntegerField(default=0)),
                ('last_scan_bad', models.IntegerField(default=0)),
                ('last_ts_checked', models.DateTimeField(blank=True, null=True)),
                ('one_wire_interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.onewireinterface')),
            ],
            options={
                'verbose_name': 'TempSensor',
                'verbose_name_plural': 'TempSensors',
            },
        ),
        migrations.CreateModel(
            name='TempSensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.tempsensor')),
            ],
            options={
                'verbose_name': 'TempSensorData',
                'verbose_name_plural': 'TempSensorData',
            },
        ),
        migrations.CreateModel(
            name='RelayData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.BooleanField()),
                ('relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.relay')),
            ],
            options={
                'verbose_name': 'RelayData',
                'verbose_name_plural': 'RelayData',
            },
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=512)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'verbose_name': 'DeviceStatus',
                'verbose_name_plural': 'DeviceStatus',
            },
        ),
        migrations.AddIndex(
            model_name='tempsensordata',
            index=models.Index(fields=['sensor', '-timestamp'], name='devices_tsensordata_sid_ts'),
        ),
        migrations.AddIndex(
            model_name='relaydata',
            index=models.Index(fields=['relay', '-timestamp'], name='sensors_relay_sid_ts'),
        ),
        migrations.AddIndex(
            model_name='devicestatus',
            index=models.Index(fields=['device', '-timestamp'], name='sensors_device_sid_ts'),
        ),
    ]
