# Generated by Django 5.1.6 on 2025-03-14 17:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_devicestatus_id_alter_onewireinterface_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SunSensor',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'SunSensor',
                'verbose_name_plural': 'SunSensors',
            },
        ),
        migrations.CreateModel(
            name='WindSensor',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'WindSensor',
                'verbose_name_plural': 'WindSensors',
            },
        ),
        migrations.CreateModel(
            name='SunSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.sunsensor')),
            ],
            options={
                'verbose_name': 'SunSensorData',
                'verbose_name_plural': 'SunSensorData',
                'indexes': [models.Index(fields=['sensor', '-timestamp'], name='devices_ssensordata_sid_ts')],
            },
        ),
        migrations.CreateModel(
            name='WindSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.windsensor')),
            ],
            options={
                'verbose_name': 'WindSensorData',
                'verbose_name_plural': 'WindSensorData',
                'indexes': [models.Index(fields=['sensor', '-timestamp'], name='devices_wsensordata_sid_ts')],
            },
        ),
    ]
