# Generated by Django 5.1.6 on 2025-03-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_sunsensor_windsensor_sunsensordata_windsensordata'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sunsensordata',
            constraint=models.UniqueConstraint(fields=('sensor', 'timestamp'), name='devices_ssensordata_unique'),
        ),
        migrations.AddConstraint(
            model_name='tempsensordata',
            constraint=models.UniqueConstraint(fields=('sensor', 'timestamp'), name='devices_tsensordata_unique'),
        ),
        migrations.AddConstraint(
            model_name='windsensordata',
            constraint=models.UniqueConstraint(fields=('sensor', 'timestamp'), name='devices_wsensordata_unique'),
        ),
    ]
