# Generated by Django 5.1.6 on 2025-03-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_sunsensordata_devices_ssensordata_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaydata',
            name='received_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sunsensordata',
            name='received_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tempsensordata',
            name='received_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='windsensordata',
            name='received_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
