# Generated by Django 2.2.6 on 2019-10-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='value',
            new_name='value_real',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='value_bool',
            field=models.NullBooleanField(),
        ),
    ]
