# Generated by Django 3.1.6 on 2021-02-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='sensors',
        ),
    ]
