# Generated by Django 2.2.6 on 2019-10-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0002_auto_20191025_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='value_bool',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='value_real',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
