# Generated by Django 2.2.6 on 2019-10-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0004_auto_20191025_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('TEMP', 'Temperature'), ('POS', 'Position'), ('ONOFF', 'On/Off')], max_length=8),
        ),
    ]
