# Generated by Django 5.1.6 on 2025-03-14 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0003_sunsensor_windsensor_sunsensordata_windsensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=512, null=True)),
                ('sensor_sun', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='devices.sunsensor')),
                ('sensor_temp', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='devices.tempsensor')),
                ('sensor_wind', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='devices.windsensor')),
            ],
            options={
                'verbose_name': 'Weather',
                'verbose_name_plural': 'Weathers',
            },
        ),
    ]
