# Generated by Django 3.1.7 on 2021-04-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('hotwater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circpump',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sensor', to='devices.tempsensor'),
        ),
        migrations.AlterField(
            model_name='waterheater',
            name='sensor_burn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sensor_burn', to='devices.tempsensor'),
        ),
        migrations.AlterField(
            model_name='waterheater',
            name='sensor_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sensor_in', to='devices.tempsensor'),
        ),
        migrations.AlterField(
            model_name='waterheater',
            name='sensor_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sensor_out', to='devices.tempsensor'),
        ),
    ]
